<a href="https://colab.research.google.com/github/tombresee/PyTorch/blob/main/ENTER/notebooks/tensor_tutorialv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [122]:
from __future__ import print_function
import torch

In [123]:
dir(torch)

['AVG',
 'AggregationType',
 'AnyType',
 'Argument',
 'ArgumentSpec',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BenchmarkConfig',
 'BenchmarkExecutionStats',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'BufferDict',
 'ByteStorage',
 'ByteTensor',
 'CONV_BN_FUSION',
 'CallStack',
 'Capsule',
 'CharStorage',
 'CharTensor',
 'ClassType',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'ComplexDoubleStorage',
 'ComplexFloatStorage',
 'ConcreteModuleType',
 'ConcreteModuleTypeBuilder',
 'CudaBFloat16StorageBase',
 'CudaBoolStorageBase',
 'CudaByteStorageBase',
 'CudaCharStorageBase',
 'CudaComplexDoubleStorageBase',
 'CudaComplexFloatStorageBase',
 'CudaDoubleStorageBase',
 'CudaFloatStorageBase',
 'CudaHalfStorageBase',
 'CudaIntStorageBase',
 'CudaLongStorageBase',
 'CudaShortStorageBase',
 'DeepCopyMemoTable',
 'DeviceObjType',
 'DictType',
 'DoubleStorage',
 'DoubleTensor',
 'ErrorReport',
 'ExecutionPlan',
 'ExtraFilesMap',
 'FatalError',
 'FileCheck',
 'FloatStorage',

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [124]:
x = torch.empty(5, 3)
print(x)

tensor([[8.2919e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [9.3233e-09, 8.0221e+17, 5.7453e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [125]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__

Construct a randomly initialized matrix:



In [126]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2709, 0.4418, 0.1935],
        [0.6829, 0.6547, 0.3868],
        [0.6922, 0.6616, 0.8053],
        [0.8367, 0.3307, 0.9885],
        [0.4422, 0.4828, 0.0281]])


Construct a matrix filled zeros and of dtype long:



In [127]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [128]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [129]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1473, -0.7373,  0.3726],
        [-0.4371, -1.1652, -1.6916],
        [-1.0850,  0.5019,  0.3709],
        [-0.7303, -2.8850,  0.4194],
        [-0.3108,  1.0556,  1.0694]])


Get its size:



In [130]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [131]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2540, -0.5598,  1.3320],
        [-0.3694, -1.0549, -1.2086],
        [-0.8553,  1.1808,  0.6785],
        [-0.4651, -2.3567,  1.2814],
        [-0.1625,  1.7904,  1.8906]])


Addition: syntax 2



In [132]:
print(torch.add(x, y))

tensor([[ 0.2540, -0.5598,  1.3320],
        [-0.3694, -1.0549, -1.2086],
        [-0.8553,  1.1808,  0.6785],
        [-0.4651, -2.3567,  1.2814],
        [-0.1625,  1.7904,  1.8906]])


Addition: providing an output tensor as argument



In [133]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2540, -0.5598,  1.3320],
        [-0.3694, -1.0549, -1.2086],
        [-0.8553,  1.1808,  0.6785],
        [-0.4651, -2.3567,  1.2814],
        [-0.1625,  1.7904,  1.8906]])


Addition: in-place



In [134]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.2540, -0.5598,  1.3320],
        [-0.3694, -1.0549, -1.2086],
        [-0.8553,  1.1808,  0.6785],
        [-0.4651, -2.3567,  1.2814],
        [-0.1625,  1.7904,  1.8906]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [135]:
print(x[:, 1])

tensor([-0.7373, -1.1652,  0.5019, -2.8850,  1.0556])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [136]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [137]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.4998])
-2.499812126159668


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [138]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [139]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [140]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [141]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [142]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

# Tensors:

In [143]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [144]:
# torch.tensor(data) creates a torch.Tensor object with the given data.

V_data = [1., 2., 3., 4., 5., 6., 7., 8., 9.]

V = torch.tensor(V_data)

print(V)

# Creates a matrix M

M_data = [[1., 2., 3.], [4., 5., 6]]

M = torch.tensor(M_data)

print(M)

print(type(M))


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
<class 'torch.Tensor'>


In [145]:

# Create a 3D tensor of size 2x2x2

T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]

T = torch.tensor(T_data)

print(T)

dir(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__

In [146]:
T

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [147]:
T.abs()

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [148]:
T.add(T)

tensor([[[ 2.,  4.],
         [ 6.,  8.]],

        [[10., 12.],
         [14., 16.]]])

In [149]:
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [150]:
#  T.allclose?

In [151]:
T.backward

<bound method Tensor.backward of tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])>

In [152]:
T.dim()

3

In [153]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [154]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [155]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
# torch.cat([x_1, x_2])


tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631],
        [-0.8923, -0.0583, -0.1955, -0.9656,  0.4224],
        [ 0.2673, -0.4212, -0.5107, -1.5727, -0.1232],
        [ 3.5870, -1.8313,  1.5987, -1.2770,  0.3255]])
tensor([[-0.4791,  1.3790,  2.5286,  0.5423,  0.1103, -2.2590,  0.6067, -0.1383],
        [ 0.4107, -0.9880, -0.9081,  0.8310, -0.2477, -0.8029,  0.2366,  0.2857]])


In [156]:
### reshaping tensors:

# Use the .view() method to reshape a tensor. This method receives heavy use, 
# because many neural network components expect their inputs to have a certain shape. 
# Often you will need to reshape before passing your data to the component.

x = torch.randn(2, 3, 4)
print(x)


print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))


tensor([[[-1.4344, -0.5008,  0.1716, -0.1600],
         [-0.5047, -1.4746, -0.3416, -0.3003],
         [ 1.2466,  0.5057,  0.9505,  1.2966]],

        [[ 0.8738, -0.5603,  1.2858,  0.8168],
         [-1.4648, -1.2629,  1.1220,  1.5663],
         [ 2.5581, -0.2334, -0.0135,  1.8606]]])
tensor([[-1.4344, -0.5008,  0.1716, -0.1600, -0.5047, -1.4746, -0.3416, -0.3003,
          1.2466,  0.5057,  0.9505,  1.2966],
        [ 0.8738, -0.5603,  1.2858,  0.8168, -1.4648, -1.2629,  1.1220,  1.5663,
          2.5581, -0.2334, -0.0135,  1.8606]])
tensor([[-1.4344, -0.5008,  0.1716, -0.1600, -0.5047, -1.4746, -0.3416, -0.3003,
          1.2466,  0.5057,  0.9505,  1.2966],
        [ 0.8738, -0.5603,  1.2858,  0.8168, -1.4648, -1.2629,  1.1220,  1.5663,
          2.5581, -0.2334, -0.0135,  1.8606]])


In [157]:

aa = [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]]
TA = torch.tensor(aa)
TA

tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]])

In [158]:
TA.view(7,2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]])

# ODD:

Computation Graphs and Automatic Differentiation
The concept of a computation graph is essential to efficient deep learning programming, because it allows you to not have to write the back propagation gradients yourself. A computation graph is simply a specification of how your data is combined to give you the output. Since the graph totally specifies what parameters were involved with which operations, it contains enough information to compute derivatives. This probably sounds vague, so let’s see what is going on using the fundamental flag requires_grad.

First, think from a programmers perspective. What is stored in the torch.Tensor objects we were creating above? Obviously the data and the shape, and maybe a few other things. But when we added two tensors together, we got an output tensor. All this output tensor knows is its data and shape. It has no idea that it was the sum of two other tensors (it could have been read in from a file, it could be the result of some other operation, etc.)


In [159]:

# Tensor factory methods have a ``requires_grad`` flag
x = torch.tensor([1., 2., 3], requires_grad=True)


# With requires_grad=True, you can still do all the operations you previously
# could
y = torch.tensor([4., 5., 6], requires_grad=True)
z = x + y

print(z)

# BUT z knows something extra.
print(z.grad_fn)

#  If requires_grad=True, the Tensor object keeps track of how it was created. Lets see it in action.


# So Tensors know what created them. z knows that it wasn’t read in from a file, it wasn’t the 
# result of a multiplication or exponential or whatever. And if you keep following z.grad_fn, 
# you will find yourself at x and y.


tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [160]:
# Lets sum up all the entries in z
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [161]:
# calling .backward() on any variable will run backprop, starting from it.
s.backward()
print(x.grad)


tensor([1., 1., 1.])


In [162]:


x = torch.randn(2, 2)
y = torch.randn(2, 2)


# By default, user created Tensors have ``requires_grad=False``
print(x.requires_grad, y.requires_grad)


z = x + y
# So you can't backprop through z
print(z.grad_fn)


# ``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
# flag in-place. The input flag defaults to ``True`` if not given.

x = x.requires_grad_()
y = y.requires_grad_()


# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)

# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)


# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?
new_z = z.detach()


# ... does new_z have information to backprop to x and y?
# NO!


print(new_z.grad_fn)
# And how could it? ``z.detach()`` returns a tensor that shares the same storage
# as ``z``, but with the computation history forgotten. It doesn't know anything
# about how it was computed.
# In essence, we have broken the Tensor away from its past history


False False
None
True
None
